// 初始种子数据：由 DBWB耗材盘点.xlsx(9月) 与 耦合段配件统计.xlsx 提取生成
// safety 默认 5 为系统占位值(safetyAuto=true)，手动设定的项 safetyAuto=false
const SEED_ITEMS = [
  {
    "id": "P0001",
    "process": "焊线工序(DBWB)",
    "equipment": "创世杰",
    "name": "LD吸嘴",
    "unit": "个",
    "stock": 9,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过8个不包含在内"
  },
  {
    "id": "P0002",
    "process": "焊线工序(DBWB)",
    "equipment": "创世杰",
    "name": "COC吸嘴",
    "unit": "个",
    "stock": 1,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过10个不包含在内"
  },
  {
    "id": "P0003",
    "process": "焊线工序(DBWB)",
    "equipment": "创世杰",
    "name": "DRI/PIC吸嘴",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过21个不包含在内"
  },
  {
    "id": "P0004",
    "process": "焊线工序(DBWB)",
    "equipment": "创世杰",
    "name": "TIA吸嘴",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过21个不包含在内"
  },
  {
    "id": "P0005",
    "process": "焊线工序(DBWB)",
    "equipment": "创世杰",
    "name": "PD吸嘴",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过21个不包含在内"
  },
  {
    "id": "P0006",
    "process": "焊线工序(DBWB)",
    "equipment": "创世杰",
    "name": "NTC/MPD吸嘴",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过14个不包含在内"
  },
  {
    "id": "P0007",
    "process": "焊线工序(DBWB)",
    "equipment": "创世杰",
    "name": "ISO吸嘴",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过22个不包含在内"
  },
  {
    "id": "P0008",
    "process": "焊线工序(DBWB)",
    "equipment": "创世杰",
    "name": "DRI点胶头",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过23个不包含在内"
  },
  {
    "id": "P0009",
    "process": "焊线工序(DBWB)",
    "equipment": "创世杰",
    "name": "COC点胶头",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过23个不包含在内"
  },
  {
    "id": "P0010",
    "process": "焊线工序(DBWB)",
    "equipment": "创世杰",
    "name": "TIA点胶头",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过22个不包含在内"
  },
  {
    "id": "P0011",
    "process": "焊线工序(DBWB)",
    "equipment": "创世杰",
    "name": "PD点胶头",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过23个不包含在内"
  },
  {
    "id": "P0012",
    "process": "焊线工序(DBWB)",
    "equipment": "创世杰",
    "name": "NTC/MPD点胶头",
    "unit": "个",
    "stock": 27,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0013",
    "process": "焊线工序(DBWB)",
    "equipment": "普莱信",
    "name": "DRI/PIC吸嘴",
    "unit": "个",
    "stock": 15,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过4个不包含在内"
  },
  {
    "id": "P0014",
    "process": "焊线工序(DBWB)",
    "equipment": "普莱信",
    "name": "COC吸嘴",
    "unit": "个",
    "stock": 13,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过4个不包含在内"
  },
  {
    "id": "P0015",
    "process": "焊线工序(DBWB)",
    "equipment": "普莱信",
    "name": "TIA吸嘴",
    "unit": "个",
    "stock": 8,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过4个不包含在内"
  },
  {
    "id": "P0016",
    "process": "焊线工序(DBWB)",
    "equipment": "普莱信",
    "name": "PD吸嘴",
    "unit": "个",
    "stock": 7,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过4个不包含在内"
  },
  {
    "id": "P0017",
    "process": "焊线工序(DBWB)",
    "equipment": "普莱信",
    "name": "NTC/MPD吸嘴",
    "unit": "个",
    "stock": 14,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过4个不包含在内"
  },
  {
    "id": "P0018",
    "process": "焊线工序(DBWB)",
    "equipment": "普莱信",
    "name": "ISO吸嘴",
    "unit": "个",
    "stock": 8,
    "safety": 5,
    "safetyAuto": true,
    "note": "ESD未过4个不包含在内"
  },
  {
    "id": "P0019",
    "process": "焊线工序(DBWB)",
    "equipment": "普莱信",
    "name": "DRI点胶头",
    "unit": "个",
    "stock": 13,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0020",
    "process": "焊线工序(DBWB)",
    "equipment": "普莱信",
    "name": "COC点胶头",
    "unit": "个",
    "stock": 14,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0021",
    "process": "焊线工序(DBWB)",
    "equipment": "普莱信",
    "name": "TIA点胶头",
    "unit": "个",
    "stock": 13,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0022",
    "process": "焊线工序(DBWB)",
    "equipment": "普莱信",
    "name": "PD点胶头",
    "unit": "个",
    "stock": 10,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0023",
    "process": "焊线工序(DBWB)",
    "equipment": "普莱信",
    "name": "NTC/MPD点胶头",
    "unit": "个",
    "stock": 8,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0024",
    "process": "焊线工序(DBWB)",
    "equipment": "普莱信",
    "name": "ISO点胶头",
    "unit": "个",
    "stock": 12,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0025",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "DRI/PIC吸嘴",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0026",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "COC吸嘴",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0027",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "TIA吸嘴",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0028",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "PD吸嘴",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0029",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "NTC/MPD吸嘴",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0030",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "ISO吸嘴",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0031",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "LD吸嘴",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0032",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "DRI点胶头",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0033",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "COC点胶头",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0034",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "TIA点胶头",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0035",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "PD点胶头",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0036",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "NTC/MPD点胶头",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0037",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "ISO点胶头",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0038",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "顶针17°*10*0.150",
    "unit": "个",
    "stock": 8,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0039",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "顶针17°*10*0.05",
    "unit": "个",
    "stock": 36,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0040",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "顶针17°*15*0.125",
    "unit": "个",
    "stock": 1,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0041",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "顶针1700-10-0.7-0.025",
    "unit": "个",
    "stock": 20,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0042",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "顶针17°*10*0.075",
    "unit": "个",
    "stock": 3,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0043",
    "process": "焊线工序(DBWB)",
    "equipment": "微见",
    "name": "1700*0.7*10*0.1",
    "unit": "个",
    "stock": 3,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0044",
    "process": "焊线工序(DBWB)",
    "equipment": "ASM焊线",
    "name": "30孔径瓷嘴",
    "unit": "个",
    "stock": 41,
    "safety": 5,
    "safetyAuto": true,
    "note": "c301"
  },
  {
    "id": "P0045",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "定位销",
    "unit": "个",
    "stock": 102,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0046",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "304圆头圆柱销",
    "unit": "个",
    "stock": 50,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0047",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "FA400G加电板",
    "unit": "个",
    "stock": 27,
    "safety": 5,
    "safetyAuto": true,
    "note": "含5个待维修"
  },
  {
    "id": "P0048",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "FA800G加电板",
    "unit": "个",
    "stock": 21,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0049",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "黑弹簧",
    "unit": "个",
    "stock": 30,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0050",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "弹簧",
    "unit": "个",
    "stock": 18,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0051",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "卡簧",
    "unit": "个",
    "stock": 16,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0052",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "垫圈",
    "unit": "个",
    "stock": 15,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0053",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "lens400G加电板",
    "unit": "个",
    "stock": 14,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0054",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "lens800G加电板",
    "unit": "个",
    "stock": 13,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0055",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "左FA固定块",
    "unit": "个",
    "stock": 12,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0056",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "光纤抬板",
    "unit": "个",
    "stock": 10,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0057",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "拔珠顶丝",
    "unit": "个",
    "stock": 10,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0058",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "软管接头",
    "unit": "个",
    "stock": 10,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0059",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "微型接头",
    "unit": "个",
    "stock": 8,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0060",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "转轴板",
    "unit": "个",
    "stock": 8,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0061",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "密封件组件",
    "unit": "个",
    "stock": 8,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0062",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "UV固定块（400G）",
    "unit": "个",
    "stock": 7,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0063",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "吸嘴",
    "unit": "个",
    "stock": 7,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0064",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "UV连接架（400G）",
    "unit": "个",
    "stock": 6,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0065",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "UV连接架（800G）",
    "unit": "个",
    "stock": 6,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0066",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "UV连接滑轨",
    "unit": "个",
    "stock": 6,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0067",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "玻璃块",
    "unit": "个",
    "stock": 6,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0068",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "限位块",
    "unit": "个",
    "stock": 6,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0069",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "DR8限位块",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0070",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "固定吸嘴",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0071",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "适配器固定",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0072",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "UV灯头",
    "unit": "个",
    "stock": 5,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0073",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "限位调节片",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0074",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "定位垫片",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0075",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "lens吸嘴",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0076",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "绝缘垫片",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0077",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "MT限位块",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0078",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "适配管",
    "unit": "个",
    "stock": 4,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0079",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "FA固定板",
    "unit": "个",
    "stock": 3,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0080",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "活动夹爪",
    "unit": "个",
    "stock": 3,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0081",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "微型接头（直通）",
    "unit": "个",
    "stock": 3,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0082",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "微型接头（1转2）",
    "unit": "个",
    "stock": 3,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0083",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "活塞缸限位",
    "unit": "个",
    "stock": 3,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0084",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "固定块",
    "unit": "个",
    "stock": 3,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0085",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "固化压头支架",
    "unit": "个",
    "stock": 2,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0086",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "磁铁",
    "unit": "个",
    "stock": 2,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0087",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "o型圈",
    "unit": "个",
    "stock": 2,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0088",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "防UV眼镜",
    "unit": "个",
    "stock": 2,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0089",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "绝缘垫",
    "unit": "个",
    "stock": 2,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0090",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "浮动连接头",
    "unit": "个",
    "stock": 2,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0091",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "料盘组件",
    "unit": "个",
    "stock": 2,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0092",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "2DR4",
    "unit": "个",
    "stock": 2,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0093",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "延长线",
    "unit": "个",
    "stock": 2,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0094",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "磁性开关",
    "unit": "个",
    "stock": 2,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0095",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "UV固定块（800G）",
    "unit": "个",
    "stock": 1,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0096",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "UV安装块",
    "unit": "个",
    "stock": 1,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0097",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "夹爪安装座",
    "unit": "个",
    "stock": 1,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0098",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "擦胶固定块",
    "unit": "个",
    "stock": 1,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0099",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "MPO夹爪安装座",
    "unit": "个",
    "stock": 1,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0100",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "TX夹爪",
    "unit": "个",
    "stock": 1,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0101",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "大容量定位片",
    "unit": "个",
    "stock": 1,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  },
  {
    "id": "P0102",
    "process": "耦合段",
    "equipment": "耦合段机台",
    "name": "58 种",
    "unit": "个",
    "stock": 505,
    "safety": 5,
    "safetyAuto": true,
    "note": ""
  }
];
